/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Debug, GNU /usr/bin/g++ 13.3.0) [github.com/toreseb/yosys at CustomDTU] */

(* cells_not_processed =  1  *)
(* src = "custom/counter.v:1.1-10.10" *)
module counter(clk, rst, en, count);
  (* src = "custom/counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "custom/counter.v:2.16-2.19" *)
  input rst;
  wire rst;
  (* src = "custom/counter.v:2.21-2.23" *)
  input en;
  wire en;
  (* src = "custom/counter.v:3.22-3.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* force_downto = 32'd1 *)
  (* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:274.23-274.25" *)
  wire [3:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:287.21-287.22" *)
  wire [3:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:270.26-270.27" *)
  wire [3:0] _02_;
  (* src = "custom/counter.v:5.5-9.35" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else if (en) count[0] <= _01_[0];
  (* src = "custom/counter.v:5.5-9.35" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else if (en) count[1] <= _02_[1];
  (* src = "custom/counter.v:5.5-9.35" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else if (en) count[2] <= _02_[2];
  (* src = "custom/counter.v:5.5-9.35" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else if (en) count[3] <= _02_[3];
  assign _01_[0] = ~count[0];
  assign _02_[1] = count[1] ^(* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:296.13-296.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:296.13-296.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:296.13-296.25" *)  _00_[2];
  assign _00_[1] = count[1] &(* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:293.27-293.63|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:240.19-240.41" *)  count[0];
  assign _00_[2] = count[2] &(* src = "custom/counter.v:9.22-9.34|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:293.27-293.63|/mnt/c/Users/Tores/MasterProject/yosys/build/share/techmap.v:248.19-248.41" *)  _00_[1];
  assign _01_[3:1] = count[3:1];
  assign _02_[0] = _01_[0];
  assign _00_[0] = count[0];
endmodule
