/* Generated by Yosys 0.68+138 (git sha1 56cf2cf41-dirty, Debug, GNU /usr/bin/g++ 13.3.0) [github.com/toreseb/yosys at main] */

(* cells_not_processed =  1  *)
(* src = "custom/absval_ref.v:1.1-6.10" *)
module absval_ref(a, y);
  (* src = "custom/absval_ref.v:2.24-2.25" *)
  input signed [3:0] a;
  wire signed [3:0] a;
  (* src = "custom/absval_ref.v:2.40-2.41" *)
  output [3:0] y;
  wire [3:0] y;
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:24.32-24.112" *)
  LUT5 #(
    .INIT(16'h1fe0)
  ) _0_ (
    .I0(a[0]),
    .I1(a[1]),
    .I2(a[3]),
    .I3(a[2]),
    .I4(1'h0),
    .O(y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:20.32-20.112" *)
  LUT5 #(
    .INIT(8'h78)
  ) _1_ (
    .I0(a[0]),
    .I1(a[3]),
    .I2(a[1]),
    .I3(1'h0),
    .I4(1'h0),
    .O(y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:24.32-24.112" *)
  LUT5 #(
    .INIT(16'h0100)
  ) _2_ (
    .I0(a[0]),
    .I1(a[1]),
    .I2(a[2]),
    .I3(a[3]),
    .I4(1'h0),
    .O(y[3])
  );
  assign y[0] = a[0];
endmodule
