/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Debug, GNU /usr/bin/g++ 13.3.0) [github.com/toreseb/yosys at CustomDTU] */

(* cells_not_processed =  1  *)
(* src = "custom/counter.v:1.1-10.10" *)
module counter(clk, rst, en, count);
  (* src = "custom/counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "custom/counter.v:2.16-2.19" *)
  input rst;
  wire rst;
  (* src = "custom/counter.v:2.21-2.23" *)
  input en;
  wire en;
  (* src = "custom/counter.v:3.22-3.27" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.13-2.14" *)
  wire _04_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.11-2.12" *)
  wire _05_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:3.12-3.13" *)
  wire _06_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.15-2.16" *)
  wire _07_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.13-2.14" *)
  wire _08_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.11-2.12" *)
  wire _09_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:3.12-3.13" *)
  wire _10_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.15-2.16" *)
  wire _11_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.13-2.14" *)
  wire _12_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.11-2.12" *)
  wire _13_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:3.12-3.13" *)
  wire _14_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.15-2.16" *)
  wire _15_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.13-2.14" *)
  wire _16_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.11-2.12" *)
  wire _17_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:3.12-3.13" *)
  wire _18_;
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:2.15-2.16" *)
  wire _19_;
  assign _00_ = 16'h7f80 >> { count[2], en, count[0], count[1] };
  assign _01_ = 8'h78 >> { count[1], en, count[0] };
  assign _02_ = 4'h6 >> { en, count[0] };
  assign _03_ = 32'd2147450880 >> { count[3], en, count[2], count[0], count[1] };
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.10-5.79" *)
  SDFF _24_ (
    .CLK(clk),
    .D(_02_),
    .O(count[0]),
    .nres(1'h0),
    .nres_prog(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.10-5.79" *)
  SDFF _25_ (
    .CLK(clk),
    .D(_01_),
    .O(count[1]),
    .nres(1'h0),
    .nres_prog(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.10-5.79" *)
  SDFF _26_ (
    .CLK(clk),
    .D(_00_),
    .O(count[2]),
    .nres(1'h0),
    .nres_prog(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.10-5.79" *)
  SDFF _27_ (
    .CLK(clk),
    .D(_03_),
    .O(count[3]),
    .nres(1'h0),
    .nres_prog(rst)
  );
endmodule
