/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Debug, GNU /usr/bin/g++ 13.3.0) [github.com/toreseb/yosys at CustomDTU] */

(* cells_not_processed =  1  *)
(* src = "custom/counter.v:1.1-10.10" *)
module counter(clk, rst, en, count);
  (* src = "custom/counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "custom/counter.v:2.16-2.19" *)
  input rst;
  wire rst;
  (* src = "custom/counter.v:2.21-2.23" *)
  input en;
  wire en;
  (* src = "custom/counter.v:3.22-3.27" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* force_downto = 32'd1 *)
  (* src = "custom/maps/cells_map.v:6.23-6.24" *)
  wire [1:0] _04_;
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:28.32-28.112" *)
  LUT5 #(
    .INIT(32'd8323200)
  ) _05_ (
    .I0(en),
    .I1(count[0]),
    .I2(count[1]),
    .I3(rst),
    .I4(count[2]),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:24.32-24.112" *)
  LUT5 #(
    .INIT(16'h0708)
  ) _06_ (
    .I0(en),
    .I1(count[0]),
    .I2(rst),
    .I3(count[1]),
    .I4(1'h0),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:20.32-20.112" *)
  LUT5 #(
    .INIT(8'h14)
  ) _07_ (
    .I0(rst),
    .I1(en),
    .I2(count[0]),
    .I3(1'h0),
    .I4(1'h0),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/maps/cells_map.v:16.32-16.112" *)
  LUT5 #(
    .INIT(4'h1)
  ) _08_ (
    .I0(_04_[0]),
    .I1(rst),
    .I2(1'h0),
    .I3(1'h0),
    .I4(1'h0),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.11-5.78" *)
  ALDFF _09_ (
    .CLK(clk),
    .D(_02_),
    .O(count[0]),
    .nres(1'hx),
    .nres_prog(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.11-5.78" *)
  ALDFF _10_ (
    .CLK(clk),
    .D(_01_),
    .O(count[1]),
    .nres(1'hx),
    .nres_prog(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.11-5.78" *)
  ALDFF _11_ (
    .CLK(clk),
    .D(_00_),
    .O(count[2]),
    .nres(1'hx),
    .nres_prog(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom/counter.v:5.5-9.35|custom/maps/ff_map.v:5.11-5.78" *)
  ALDFF _12_ (
    .CLK(clk),
    .D(_03_),
    .O(count[3]),
    .nres(1'hx),
    .nres_prog(1'h1)
  );
  assign _04_[1] = rst;
endmodule
